### ISSUE TITLE
Metric calculation

### ISSUE THREAD

**Issue by mer1988** [INK-USC/RENet#4]
Hi, I think the way the baseline  metrics Hits@X and MR and MMR are calculated has a problem as follows:

1. TripleDict contains ground truth about what triples are known, but this dict is agnostic of time, it is created in utils.py and totally ignore the time dimension. Eg. (s,o,p) = True regardles of the time the query is issued. 

2. When you evaluate the ranking is based solely on the existence of (s,p,o) in triplesDict. Therefore if the quadruple to predict is (s,p,o,t) and (s,p,o) in triplesDict then is classified as true when it can be true in t1 but not in t2. 

I have made a few changes to address this issue, mainly add a time field to the triplesDict and a realTime (rt) field to the quads object, so at test time we can easily search for (s,p,o,t) in tripleDict instead of (s,p,o).  

Do you have any thoughts about which one is the correct evaluation? Is there something i am missing from your implementation?

**Comment by mer1988** [comment]
I think you have a similar error in the filtered setting of the proposed method evaluation. Please also comment on this

**Comment by woojeongjin** [comment]
Hi, 
1. Static methods are agnostic of time. Thus, we don't include time information for static methods.
2. We assume that static methods cannot use time information.

Your idea is also possible. But we decided not to use time information for static methods since they cannot utilize time information.

**Comment by mer1988** [comment]
TA_transe, TA_Distmult are not agnostic of time. You also have the same problem when calculating the filtered version of the metrics for your proposed method. In model.py -> Evaluate_filter you are not taking time into consideration. 

`      s_id = torch.nonzero(all_triplets[:, 0] == s).view(-1)
        idx = torch.nonzero(all_triplets[s_id, 1] == r).view(-1)
        idx = s_id[idx]
        idx = all_triplets[idx, 2]
        ob_pred[idx] = 0
        ob_pred[o_label] = ground
`

When you apply this filter, which means do not consider any object that i already know to be true, you don't include time, and you are filtering more elements than you should. Maybe something like this will avoid cutting off elements that should not be filtered. 

`
        t_id = torch.nonzero(all_triplets[:, 3] == t).view(-1)
        index = torch.nonzero(all_triplets[t_id, 0] == s).view(-1)
        s_id = t_id[index]
        index = torch.nonzero(all_triplets[s_id, 1] == r).view(-1)
        index = s_id[index]
        idx = all_triplets[index, 2]
        ob_pred[idx] = 0
        ob_pred[o_label] = ground`

**Comment by woojeongjin** [comment]
This is not a problem since we use the same metrics for all methods. If we use different metrics then it is not a fair comparison.
Also, other papers including HyTE and know-evolve use this metric.

If we include time in the filtered setting, then the filtered version will be equivalent to the raw version since (times_train < times_test).
You can refer to the results with the raw setting in the paper in this case.
